config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '',
                    :path_names => { :sign_in => 'Login', :sign_out => 'Logout', :edit => 'Profile'},
                    :controllers => {:registrations => 'registrations'}
  root 'pages#home'
  resources :users, only: [:show]
  resources :rooms
  resources :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :room
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  
  validates :home_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: { maximum: 75 }
  validates :summary, presence: true, length: { maximum: 600 }
  validates :address, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 5 }
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :fullname, presence: true, length: { maximum: 50 }
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/default_image.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  has_many :rooms
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller? 
  
  protected
  #Authorize variable fullname for devise module to sign up and update profile
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :avatar, :phone_number, :description, :email, :password, :password_confirmation])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def destroy
    #correspond à l’id de la photo concernée
    @photo = Photo.find(params[:id])
    room = @photo.room
    
    @photo.destroy
    #réactualise la liste des photos de ce logement
    @photos = Photo.where(room_id: room.id)
    #pour la suppression immédiate 
    respond_to :js
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

protected
  #Update Devise without password confirmation
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @rooms = current_user.rooms
  end
  
  def new
    @room = current_user.rooms.build
  end
  
  def create
    @room = current_user.rooms.build(room_params)
      if @room.save
        if params[:images]
          params[:images].each do |i|
            @room.photos.create(image: i)
          end
        end
        @photos = @room.photos
        redirect_to  edit_room_path(@room), notice: 'Votre annonce a ete ajoute avec succes'
      else
        render :new
      end
  end

  def show
    @photos = @room.photos
  end

  def edit
    @photos = @room.photos
  end

  def update
    if @room.update(room_params)
      if params[:images]
        params[:images].each do |i|
          @room.photos.create(image: i)
        end
      end
        @photos = @room.photos
          redirect_to edit_room_path(@room), notice:'Modification enregistree...'
    else
      render :edit
    end
  end
  
private
  def set_room
   @room = Room.find(params[:id])
  end
  
  def room_params
     params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_wifi, :is_tv, :is_closet, :is_shampoo, :is_breakfast, :is_heating, :is_air, :is_kitchen, :price, :active)
  end
  
  def require_same_user
    if current_user.id != @room.user_id
      flash[:danger] = "Vous n'avez pas le droit de modifier cette page"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    user.avatar.url
  end
end

app/views/layouts/_navigation.html.erb
<!-- Static navbar -->
  <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Airbnb', root_path, {:class=>'navbar-brand'} %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              
              <li>
                <%= link_to new_room_path do %>
                  <i class="fa fa-home fa-lg"></i>Devenez Hote
                <% end %>
              </li>
              
              <% if (!user_signed_in?) %>
                <li><%= link_to "Inscription", new_user_registration_path  %></li>
                <li><%= link_to "Sign In", new_user_session_path  %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag avatar_url(current_user), class:'img-circle avatar-small'%><%= current_user.fullname %><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Mes voyages', root_path%></li>
                    <li><%= link_to 'Editer mon profile', edit_user_registration_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
                  </ul>
                </li>
              <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
</head>
<body>

<%= render 'layouts/navigation'%>
<%= render 'shared/message'%>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome</h1>

<%= link_to "Inscription", new_user_registration_path  %>
<%= link_to "Sign In", new_user_session_path  %>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete  %>

app/views/photos/_list.html.erb
<% if @photos %>
  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class= "panel-body">
            <span class="pull-right">
              <%= link_to photo, remote: true, method: :delete, data: {confirm: "Attention, vous allez supprimer cette photo!"} do %>
                <i class= "fa fa-times fa-lg"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/rooms/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Devenez hote AirBB
  </div>
  <div class="panel-body">
    <div class="container">
      
      <%= form_for @room, html: { multipart: true } do |f| %>
        <%= render 'shared/errors' %>
      
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Genre d'habitation</label>
              <%= f.select :home_type, [['Maison','Maison'],['Appartement','Appartement'], ['B&B','B&B']], 
              id: 'home_type', prompt:'A selectionner...', class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Type de logement</label>
              <%= f.select :room_type, [['Logement entier','Logement entier'],['Chambre privee','Chambre privee'], ['Chambre partagee','Chambre partagee']],prompt:'A selectionner...', class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Combien de voyageurs ?</label>
              <%= f.select :accommodate, [['1 voyageur',1],['2 voyageurs',2], ['3 voyageurs',3],['4 voyageurs',4],['5 voyageurs',5], ['6 voyageurs',6]], 
              prompt:'A selectionner...', class: 'form-control' %>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Chambres</label>
              <%= f.select :bed_room, [['1',1],['2',2], ['3',3], ['4',4]],prompt:'A selectionner...', class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Salle de bains</label>
              <%= f.select :bath_room, [['1',1],['2',2], ['3',3],['4',4]],prompt:'A selectionner...', class: 'form-control' %>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="form-group">
            <label>Donnez un nom au logement</label>
            <%= f.text_field :listing_name, placeholder: "Titre de l'annonce", class: 'form-control' %>
          </div>
        </div>
        
        <div class="row">
          <div class="form-group">
            <label>Resume</label>
            <%= f.text_area :summary, placeholder: "Decrivez le decor, ambiance, proximite", class: 'form-control' %>
          </div>
        </div>
        
        <div class="row">
          <div class="form-group">
            <label>Adresse</label>
            <%= f.text_field :address, placeholder: "Ou est situe votre logement", class: 'form-control' %>
          </div>
        </div>
        
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <span class= 'btn btn-default btn-file'>
                <i class="fa fa-cloud-upload fa-lg"></i>Telechargez vos photos
                <%= file_field_tag "images[]", type: :file, multiple:true %>
              </span>
            </div>
          </div>
        </div>
        
        <div class="photos"><%= render 'photos/list' %></div>
        
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_wifi %> WIFI
            </div>
            <div class="form-group">
              <%= f.check_box :is_tv %> Television
            </div>
            <div class="form-group">
              <%= f.check_box :is_closet %> Closet
            </div>
            <div class="form-group">
              <%= f.check_box :is_shampoo %> Shampoo
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_breakfast %> Petit dej
            </div>
            <div class="form-group">
              <%= f.check_box :is_heating %> chauffage
            </div>
            <div class="form-group">
              <%= f.check_box :is_air %> Air conditionne
            </div>
            <div class="form-group">
              <%= f.check_box :is_kitchen %> Cuisine
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label>Prix par nuit</label>
              <div class="input-group">
                <%= f.text_field :price, placeholder: 'ex: 45 euros', class: 'form-control' %>
                <div class= 'input-group-addon'>Euros</div>
              </div>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="form-group">
            <%= f.check_box :active %> Annonce Active
          </div>
        </div>
        
        <div class="actions">
          <%= f.submit "Je valide mon annonce", class: "btn btn-primary" %>
        </div>
    
    <% end %>
  
  </div>
</div>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link active" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes annonces </div>
            <div class="panel-body">
                <% @rooms.each do |room| %>
                    <div class="row">
                        <div class="col-md-2">
                            <%= image_tag room.photos[0].image.url(:thumb) if room.photos.length > 0 %>
                        </div>
                        <div class="col-md-7">
                            <h4><%= room.listing_name %></h4>
                        </div>
                        <div class="col-md-3 right">
                            <%= link_to "Mettre a jour", edit_room_path(room), class: "btn btn-primary" %>
                        </div>
                    </div>
                    <hr />
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <!--Photo principale de l'annonce-->
    <div class="row">
            <div class="col-md-12">
                <%= image_tag @photos[0].image.url(), class: "img-responsive" if @photos.length > 0  %>
            </div>
        </div>
        
    <!--Information principale-->
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-3 text-center">
            <%= image_tag avatar_url(@room.user), class: "img-circle avatar-large " %>
            <br>
            <br>
            <%= @room.user.fullname %>
          </div>
          <div class="col-md-9">
            <h4><%= @room.listing_name %></h4>
            <%= @room.address %>
            <div class="row text-center row-space-1">
              <div class="col-sm-3">
                <i class= "fa fa-home fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class= "fa fa-users fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class= "fa fa-bed fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class= "fa fa-bath fa-2x"></i>
              </div>
            </div>
            <div class="row text-center">
              <div class="col-sm-3">
                <%= @room.home_type %>
              </div>
              <div class="col-sm-3">
                <%= @room.accommodate %><%= @room.accommodate > 1 ? "voyageurs":"voyageur" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bed_room %><%= @room.bed_room > 1 ? "lits":"lit" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bath_room %><%= @room.bath_room > 1 ? "salles de bains":"salle de bain" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <!-- Formulaire de réservation -->
      </div>
    </div>

    <!--Description du logement-->
    <div class="row">
      <div class="col-md-12">
        <h2>A propos de ce logement</h2>
        <p><%= @room.summary %></p>
      </div>
    </div>
    
    <!--Equipement-->
    <div class="row">
      <div class="col-md-2">
        <p>Equipements</p>
      </div>
        <div class="col-md-10">
          <div class="row">
            <div class="col-md-6">
              <ul class="equipements">
                <li class="<%= "text-line-through" if !@room.is_wifi %>">WIFI</li>
                <li class="<%= "text-line-through" if !@room.is_tv %>">Télévision</li>
                <li class="<%= "text-line-through" if !@room.is_closet %>">Penderie/Commode</li>
                <li class="<%= "text-line-through" if !@room.is_shampoo %>">Shampoo</li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul class="equipements">
                <li class="<%= "text-line-through" if !@room.is_kitchen %>">Cuisine</li>
                <li class="<%= "text-line-through" if !@room.is_breakfast %>">Petit dej</li>
                <li class="<%= "text-line-through" if !@room.is_heating %>">Chauffage</li>
                <li class="<%= "text-line-through" if !@room.is_air %>">Air conditionné</li>
              </ul>
            </div>
          </div>
        </div>
    </div>
    
    <!--Carousel-->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!--Indicators-->
            <% if @photos %>
              <% @photos.each do |photo| %>
              <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>" class="active"></li>
              </ol>
              <% end %>
            <% end %>
          
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <% if @photos %>
                <% @photos.each do |photo| %>
                  <div class="item <%= "active" if photo.id == @photos[0].id %>">
                    <%= image_tag photo.image.url() %>
                  </div>
                <% end %>
              <% end %>
            </div>
    
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Précédent</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Suivant</span>
            </a>
        </div>
      </div>
    </div><br/>
    
    <!--Google Maps-->
    <div class="row">
      <div class="col-md-12">
        <div id="map"></div>
          <style>
           #map {
            height: 400px;
            width: 100%;
             }
          </style>
          <script>
            function initMap() {
              var uluru = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %> };
              var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 15,
                center: uluru
              });
              var marker = new google.maps.Marker({
                position: uluru,
                map: map
              });
            }
          </script>
          <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5k8Jp4QQrAGtWqHgyx75jGzwkAgRj79U&callback=initMap">
          </script>
      </div>
    </div>
    
    <!-- Logement à proximite-->
    <h3>A proximité...</h3>
    <div class="row">
      <% for room in @room.nearbys(2).limit(3) %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
          </div>
          <div class="panel-body">
            <%= link_to room.listing_name, room %><br>
            (à <%= (room.distance*1.6).round(2) %> km)
          </div>
        </div>
      </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>
    <script type='text/javascript'>
        <% resource.errors.full_messages.each do |msg| %>
            toastr.error('<%= msg %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_errors.html.erb
<% unless @room.errors.empty? %>
    <script type='text/javascript'>
        <% @room.errors.full_messages.each do |msg| %>
            toastr.error('<%= msg %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type= 'text/javascript'>
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>

<% end %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-3">
        <%= image_tag avatar_url(@user), class: 'avatar-full' %>
    
        <div class="panel panel-default">
            <div class="panel-heading">verification</div>
                <div class="panel-body">
                    Email: <%= @user.email %> <br />
                    Tel: <%= @user.phone_number %>
                </div>
        </div>
    </div>
    <div class="col-md-9">
        <h2><%= @user.fullname %></h2>
        <div class="description row-space-3">
            <%= @user.description %>
        </div>
    </div>
</div>